#!/bin/bash

# when the program is called from a non X environment, handle the mouse
# maybe an other choice is better

if test -z "${DISPLAY}"
then
    export DISPLAY=:0.0
fi

XDG_CONFIG_HOME="/userdata/system/.config" XDG_DATA_HOME="/userdata/system/.config" XDG_CACHE_HOME="/userdata/system/.cache" QT_QPA_PLATFORM="xcb" /userdata/system/switch/suyu.AppImage -platform xcb
